### ISSUE TITLE
clean package error

### ISSUE THREAD

**Issue by ouaazizdriss** [paycii/WhatTheChatSays#1]
When executing mvn clean package command the empty test generates an error:
`Errors: 
[ERROR]   SadiquiApplicationTests.contextLoads » IllegalState Failed to load Application...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
`

it works when test class is deleted

**Comment by paycii** [comment]
Please try this when buildin "mvn clean package -Dchat_api_token=token"

Le mar. 31 janv. 2023, 14:21, ouaazizdriss ***@***.***> a
écrit :
